
var keysTranslation:[String:String] = [
    "email_or_mobile":"رقم الهاتف او البريد الالكتروني",
    "password":"كلمة المرور",
    "forget_password":"نسيت كلمة المرور",
    "login":"تسجيل دخول",
    "register":"تسجيل جديد",
    "sign":"تسجيل",
    "login_with_facebook":"التسجيل بواسطة الفيسبوك",
    "icPersonAdd":"icPersonAdd",
    "icFacebook":"icFacebook",
    "backEn":"back",
    "menuEn":"menu",
    "name":"الاسم",
    "email":"البريد الإلكتروني",
    "mobile":"رقم الجوال",
    "confirmation_password":"إعادة كلمة المرور",
    "confirm_password":"إعادة كلمة المرور",
    "set_your_location":"قم بتحديد الموقع",
    "city":"المدينة",
    "district":"المنطقة",
    "show_restaurant":"عرض المطاعم",
    "your_registration_request_has_been_sent":"تم إرسال طلب التسجيل",
    "Your account will be activated from the administration after which you will be received Activation email You registered it":"سيتم تفعيل حسابك من الادارة بعدها سيصلك رسالة بالتفعيل على بريدك الإلكتروني الذي قمت بالتسجيل به",
    "ok":"حسنأ",
    "search_for_city":"ابحث عن المدينة",
    "search_in_district":"ابحث عن منطقة",
    "location":"موقعك",
    "search_in_chiefs":"ابحث عن أحد المطابخ أو الأطباق",
    "best_chiefs":"المطابخ المميزة",
    "show_all":"عرض الكل",
    "nearest_chiefs":"المطابخ القريبة منك",
    "adEn":"adAr",
    "minute":"دقيقة",
    "show_result":"عرض النتائج",
    "chief_type":"نوع المطبخ",
    "sort_by":"ترتيب حسب",
    "chiefs_filters":"فرز المطابخ",
    "cancel":"الغاء",
    "agree":"موافق",
    "accept":"قبول",
    "address":"العنوان",
    "total_price:_":"إجمالي الطلب :",
    "delivery_cost:_":"سعر خدمة التوصيل :",
    "follow_the_order":"متابعة الطلب",
    "order_now":"أطلب الآن",
    "offers":"العروض",
    "cart":"السلة",
    "SR":"ريال",
    "add_to_cart":"أضف الى السلة",
    "search":"بحث",
    "about":"حول",
    "menu":"قائمة الطعام",
    "rate":"التقييم",
    "description":"وصف",
    "minimum_order":"الحد الادنى للطلب",
    "delivery_cost":"سعر خدمة التوصيل",
    "total_price":"اجمالي الطلب",
    "all":"الكل",
    "default":"افتراضي",
    "maximum_price_in_minimum_order":"الأكثر سعراً فى الحد الأدنى للطلب",
    "loawest_price_in_minimum_order":"الأقل سعراً فى الحد الأدنى للطلب",
    "fast_delivery":"الأسرع فى توصيل الطلب",
    "top_rate":"الأعلى تقييماً",
    "icArrowBlackAr":"icArrow",
    "arrowEn":"arrow",
    
    "street":"الشارع",
    "continue_shopping":"مواصلة التسوق",
    "follow_your_request_here":"تابع طلبك هنا",
    "order_number:_":"رقم الطلب : ",
    "order_number":"رقم الطلب",
    "order_send_successfully":"تم إرسال طلب بنجاح",
    "send_order":"إرسال الطلب",
    "flat_number_(_optinal_)":"رقم الشقة (إختياري)",
    "number_of_building":"رقم أو اسم العمارة",
    
    "Note The delivery rate will change if you change the city and region":"ملحوظة سيتم تغير سعر التوصيل في حالة التعديل علي المدينة والمنطقة",
    "region_displaing_here":"المنطقة تعرض وتكتب هنا",
    "city_displaing_here":"المدينة تعرض وتكتب هنا",
    "chief_is:_":"يقدمها لك مطبخ :",
    
    
    "orders":"الطلبات",
    "upcoming":"الحالية",
    "previous":"السابقة",
    "there_are_no_current_orders":"لا توجد طلبات حالية",
    "ask_for_your_favorite_food_now":"اطلب طعامك المفضل الان",
    "show_order_details":"عرض تفاصيل الطلب",
    "give_us_your_opinion":"اعطنا رأيك",
    "later":"لاحقاً",
    "order_date":"تاريخ الطلب",
    "order_detail":"تفاصيل الطلب",
    "follow_the_status_of_your_order":"تابع حالة طلبك",
    "price":"السعر",
    "order_status":"حالة الطلب",
    "send":"إرسال",
    "favorites":"المفضلة",
    "app_language":"لغة التطبيق",
    "contact_us":"اتصل بنا",
    "about_app":"عن التطبيق",
    "usage_policy":"سياسة الاستخدام",
    "share_app":"مشاركة التطبيق",
    "profile":"الملف الشخصي",
    "my_profile":"بيانات حسابي",
    "edit_password":"تعديل كلمة المرور",
    "logout":"تسجيل خروج",
    "save":"حفظ",
    "old_password":"كلمة المرور القديمة",
    "new_password":"كلمة المرور الجديدة",
    "confirmation_new_password":"إعادة كلمة المرور الجديدة",
    "email_us":"راسلنا عبر البريد الإلكتروني",
    "submit_a_suggestion":"إرسال مقترح",
    "submit_a_complain":"إرسال شكوى",
    "what_is_your_suggestion":"ما هو اقتراحك",
    "the_text_of_the_complaint":"نص الشكوى",
    "camera":"الكاميرا",
    "gallery":"المعرض",
    "choose_image":"اختر صورة",
    "you_don't_have_camera":"عفوا ليس لديك كاميرا",
    "warning":"انذار",
    "update":"تعديل",
    "delete":"حذف",
    "update_profile":"تعديل بياناتي",
    "waiting_to_accept":"في انتظار الموافقة",
    "processing_your_order":"جاري تجهيز طلبك",
    "delivering_your_order":"جاري توصيل طلبك",
    "your_order_is_deliveried":"تم توصيل طلبك",
    "you_order_is_received":"تم استلامها",
    "Designed and Developed by ATIAF Integrated Solutions":"تصميم وتطوير شركة أطياف للحلول المتكاملة",
    "عربي":"english",
    "english":"عربي",
    "does_not_match":"غير متطابق",
    "this_field_is_required":"هذا الحقل مطلوب",
    "must_be_a_valid_email_address":"يجب ان يحتوي علي بريد الكتروني صحيح",
    "login_success":"تم تسجيل الدخول بنجاح",
    "logout_success":"تم تسجيل الخروج بنجاح",
    "code":"رمز التفعيل",
    "updated_successfully":"تم التعديل بنجاح",
    "reset_successfully":"تم استعادة كلمة السر",
    "Dear Customer Design has been sent to you to pay the agreed price to download the design":"عزيزي العميل تم إرسال التصميم عليك بدفع السعر المتفق عليه  لتحميل التصميم",
    
    "select_the_price_setting_by_the_designer":"سيتم تحديد السعر من قبل المصمم",
    "your_rate":"تقييمك",
    "no_rate":"لم يتم التقييم",
    "first_name":"الاسم الأول",
    "last_name":"الاسم الأخير",
    "phone":"رقم الهاتف",
    "enter_password":"أدخل كلمة المرور",
    "do_you_have_a_question_?":"هل لديك سؤال ؟",
    "send_message":"إرسال رسالة",
    "your_name":"أسمك",
    "your_email":"بريدك الإلكتروني",
    "subject":"الموضوع",
    "your_message":"رسالتك",
    "password_incorrect":"خطأ في كلمة السر",
    "confirmation_password_must_equal_password":"تاكيد كلمة السر يجب ان تطابق كلمة السر",
    "invalid_email":"البريد الألكتروني",
    "invalid_code":"رمز التفعيل خاطيء",
    "messages":"الرسائل",
    "message_detail":"محتوي الرسالة",
    "welcome_in":"مرحباً بك في",
    "login_for_continue":"سجل الدخول للمتابعة",
    "you_dont_have_an_account_?":"ليس لديك حساب سابقاً؟",
    "email_or_phone":"البريد الإلكتروني أو رقم الهاتف",
    "top_desingers_rate":"المصممين الأعلى تقييما",
    "last_added_desinges":"تصاميم تم اضافتهم حديثاً",
    "all_categories":"كل الفئات",
   
    
    "size":"المقاس",
    "color":"اللون",
    "quantity":"العدد",
    "near_me":"بالقرب مني",
    "welcome":"مرحباً بك",
    "choose_size":"اختر المقاس",
    "set_custom_size":"تحديد مقاس خاص",
    "choose_color":"اختر اللون",
    "choose_quantity":"حدد الكمية",
    "saved_addresses":"العناوين المحفوظة",
    "new_address":"عنوان جديد",
    "building_name":"اسم العمارة / المنزل ",
    "floor":"الطابق / الدور",
    "continue":"متابعة",
    "delivery_to":"يشحن إلى",
    "your_order":"طلبك",
    "note":"ملاحظة",
    "payment_summary":"ملخص الدفع",
    "total_order_:":"الطلب الكلي :",
    "delivery_cost_:":"رسوم التوصيل :",
    "total_price_:":"المبلغ الإجمالي :",
    "select_payment_method":"إختر طريقة الدفع",
    "cash_on_delivery":"الدفع عند الاستلام",
    "visa":"فيزا",
    
    "confirm_order":"تأكيد الطلب",
    "thank_you":"شكراً لك",
    "your_order_send_successfully":"تم ارسال طلبك بنجاح",
    "follow_your_order":"تتبع طلبك هنا",
    "request_custom_design":"طلب رسم تصميم",
    "model_type":"نوع الموديل",
    "model_tall":"طول الموديل",
    "shape":"الشكل",
    "sleeve_type":"نوع الأكمام",
    "Please specify the type of fabric and model details to be designed":"نرجوا ذكر نوع القماش وتفاصيل الموديل المراد تصميمه",
    "settings":"الإعدادات",
    "my_addresses":"قائمة العناوين",
    "add_new_address":"اضافة عنوان جديد",
    "add":"اضافة",
    "done":"تم",
    "add_your_comment":"أضف تعليقك أو رأيك",
    "my_orders":"طلباتي",
    "order_number_:":"رقم الطلب :",
    "payment_method_:":"طريقة الدفع :",
    "order_status_:":"حالة الطلب :",
    "call":"اتصال",
    "cancel_order":"إلغاء الطلب",
    "request_design_fee":"طلب رسم تصميم",
    "model_type_:":"نوع الموديل :",
    "model_tall_:":"طول الموديل :",
    "shape_:":"الشكل :",
    "sleeve_:":"الأكمام :",
    "email_:":"بريد إلكتروني :",
    "download_design":"تحميل التصميم",
    "price_:":"السعر :",
    "about_us":"عن التطبيق",
    "paid":"دفع",
    "home":"الرئيسية",
    "info":"حول",
    "designes":"التصاميم",
    "comments":"التقييمات",
    "CM":"سم",
    "write_note_here":"اكتب ملاحظاتك هنا",
    "order_summary":"ملخص الطلب",
    "size_:":"المقاس :",
    "color_:":"اللون:",
    "quantity_:":"الكمية :",
    "payment":"الدفع",
    "there_are_currently_no_requests":"لا يوجد اي طلبات حالية الان",
    "my_location":"موقعي علي الخريطة",
    "arrowLeft":"arrowRight",
    "arrowRight":"arrowLeft",
    "register_done":"تم التسجيل بنجاح",
    
    "welcome_in_jalab":"مرحباً بكم في جلاَّب",
    "create_new_account":"إنشاء حساب جديد",
    "sign_as_guest":"الدخول كزائر",
    "Enter your mobile number to create a new account":"أدخل رقم جوالك لإنشاء حساب جديد",
    "You will receive a text message with activation code on":"ستصلك رسالة نصية بكود التفعيل على",
    "Your mobile number":"رقم الجوال الخاص بك",
    "verify":"تحقق",
    "account_type":"نوع الحساب",
    "select_account_type":"اختار نوع الحساب",
    "individual":"فرد",
    "individuals":"الأفراد",
    "organization":"مؤسسة",
    "organizations":"المؤسسات",
    
    "categories":"الاقسام",
    "ads":"الاعلانات",
    "advertisers":"المعلنين",
    "requests":"الطلبات",
    "auction":"المزاد",
    "notifications":"الاشعارات",
    "best_offers":"اميز العروض",
    "search_options":"خيارات البحث",
    "icBackEn":"icBack",
    "connect with advertiser":"تواصل مع المعلن",
    "watch":"مشاهدة",
    "add_comment":"اضف تعليقك",
    "whatsapp":"واتس أب",
    "follow":"متابعة",
    "is_sold":"تم البيع",
    "not_sold":"لم يتم البيع",
    "ad_status":"حالة الأعلان",
    "follower":"متابع",
    "write_your_comment_here":"اكتب تعليقك هنا",
    "main_categories":"الفئات الرئيسية",
    "sub_categories":"الفئات الفرعية",
    "ad":"اعلان",
    "select_main_category":"حدد الفئة الرئيسية",
    "select_sub_category":"حدد الفئة الفرعية",
    "auction_end_at_:":"ينتهي المزاد في :",
    "make_offer":"تقديم عرض",
    "current_price":"سعر الحالي",
    "maximum_for_auction":"الحد الأقصي للمزاد",
    "auction_end_at":"ينتهي المزاد في",
    "auction_status":"حالة المزاد",
    "Man does not utter any word except that with him is an observer prepared":"مَّا يَلْفِظُ مِن قَوْلٍ إِلَّا لَدَيْهِ رَقِيبٌ عَتِيدٌ",
    "your_offer":"عرضك",
    "auctions":"المزادات",
    "report_for_ad":"ابلاغ عن أعلان",
    "report_for_request":"ابلاغ عن طلب",
    "report_for_auction":"إبلاغ عن المزاد",
    "min":"د",
    "sec":"ث",
    "hour":"ساعة",
    "maximum auction limit reached":"تم الوصول للحد الأقصي للمزاد",
    "auction_end_:":"انتهى المزاد :",
    "bids":"المزايدات",
    "not_found_any_bids":"لا يوجد اي مزايدات",
    "price_must_be_a_number":"العرض يجب ان يكون رقم فقط",
    "commiucation_ways":"طرق الاتصال",
    "approve message text":"الموافقة على نص الرسالة",
    "section":"بالقّسَم",
    "add_ad":"اضافة اعلان",
    "add_request":"اضافة طلب",
    "add_auction":"اضافة مزاد",
    "ads_free":"اعلانات مجانية",
    "you_have":"لديك",
    "you_can_attach_until_5_pictures":"يمكنك إرفاق حتي 5 صور",
    "packages_offer":"عرض الباقات",
    "remaining_ads":"متبقي من الاعلانات",
    "ad_name":"اسم الأعلان",
    "main_category":"الفئة الرئيسية",
    "sub_category":"الفئة الفرعية",
    "sub_sub_category":"الفئة تحت الفرعية",
    "subscribe":"اشترك",
    "alert":"تنبيه",
    "package_offer":"عرض الباقات",
    "please_accept_the_section":"من فضلك قم بالموافقة علي القّسَم",
    "packages":"الباقات",
    "number_of_ads_:":"عدد الأعلانات :",
    "add_order":"اضافة الطلب",
    "auction_name":"اسم المزاد",
    "minimum_auction":"الحد الأدنى للمزايدة",
    "maximum_auction":"الحد الأقصى للمزايدة",
    "date_auction_end":"موعد انتهاء المزاد",
    "not_more_than_24_hour":"لا يزيد عن 24 ساعة",
    "select_category":"اختار القسم",
    "select_ways":"اختار طرق التواصل",
    "select_end_date":"اختار تاريخ الأنتهاء",
    "select_city":"اختار المدينة",
    "please_select_the_category":"من فضلك اختار القسم",
    "please_select_the_city":"من فضلك اختار المدينة",
    "please_select_at_least_1_image":"من فضلك اختار علي الاقل صورة",
    "my_ads":"اعلاناتي",
    "my_categories":"اقسامي",
    "banks":"حسابات البنوك",
    "current_package_:":"الباقة الحالية :",
    "ads_number_:":"عدد الاعلانات :",
    "free_ads_number_:":"عدد الاعلانات المجانية :",
    "show_packages":"عرض الباقات",
    "change_language":"تغيير اللغة",
    "update_name":"تعديل الأسم",
    "update_email":"تعديل البريد الألكتروني",
    "update_mobile":"تعديل رقم الهاتف",
    "update_account_type":"تعديل نوع الحساب",
    "edit":"تعديل",
    "more":"المزيد",
    "are_you_sure":"هل انت متأكد",
    "delete_photo":"مسح صورة",
    "change_status":"تغيير الحالة",
    "sold":"قد تم البيع",
    "not_found_ads":"لاتوجد اعلانات",
    "send_a_inquiry":"إرسال إستفسار",
    "Send_a_complaint":"إرسال شكوى",
    "inquiry":"الإستفسار",
    "complaint":"الشكوي",
    "message_field_is_required":"حقل الرسالة مطلوب",
    "the_login_is_required":"تسجيل الدخول مطلوب",
    "your_mobile_number":"رقم الجوال الخاص بك",
    "send_the_code_again":"إرسال الكود مرة اخرى",
    "register_successfully":"تم التسجيل بنجاح",
    "you_are_onwer_this_ad":"انت صاحب الأعلان",
    "you_are_onwer_this_auction":"انت صاحب المزاد",
    "type_the_problem_here":"اكتب المشكلة هنا",
    "not_found_any_category":"لا يوجد اي اقسام",
    "":"",
]



public func translate(_ key:String)->String{
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(key)
}
public func translate(_ item:String?,_ key:String)->String{
    var itemNew = ""
    if(item != nil){
        itemNew = item!
    }
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(item: itemNew, key)
}
public func translate(_ item:String?,_ key:String,_ orderable:Bool)->String{
    var itemNew = ""
    if(item != nil){
        itemNew = item!
    }
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(item: itemNew, key, orderable: orderable)
}
public func initLang(){
    LocalizationHelper.initLang()
}
public func getAppLang()->String{
    return LocalizationHelper.getAppLang()
}
public func setAppLang(_ lang:String)->String{
    return LocalizationHelper.setAppLang(lang)
}
